#[[contact]]
#name = "Address"
#address = "4923 Market Street, Orlando FL"
#icon = "fa-map-marked-alt"

[[contact]]
name = "Email"
address = """<a href="mailto:josh@datasophos.co">josh@datasophos.co</a>"""
icon = "fa-envelope"

[[social]]
icon = "fa-github"
url = "https://github.com/datasophos"

#[[contact]]
#name = "Phone"
#address = "+1 (555) 902-8832"
#icon = "fa-mobile-alt"
#[[social]]
#icon = "fa-mastodon"
#url = "#!"
#[[social]]
#icon = "fa-facebook-f"
#url = "#!"
