#[[contact]]
#name = "Address"
#address = "4923 Market Street, Orlando FL"
#icon = "fa-map-marked-alt"

[[contact]]
name = "Email"
address = """<a href="mailto:josh@datasophos.co">josh@datasophos.co</a>"""
icon = "fa-envelope"
icon_pack = "fas"

[[contact]]
name = "Online meeting"
address = """<a href="" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/josh-datasophos/30min?primary_color=1a4480'});return false;">Schedule a call</a>"""
icon = "fa-calendar-days"
icon_pack = "fas"

[[contact]]
name = "Find us on Github"
icon = "fa-github"
address = """<a href="https://github.com/datasophos" target="_blank">datasophos</a>"""
icon_pack = "fab"

#[[contact]]
#name = "Phone"
#address = "+1 (555) 902-8832"
#icon = "fa-mobile-alt"
#[[social]]
#icon = "fa-mastodon"
#url = "#!"
#[[social]]
#icon = "fa-facebook-f"
#url = "#!"
